### ISSUE TITLE
Why not commit Buck files to the repo?

### ISSUE THREAD

**Issue by nkoroste** [uber-common/android-build-eval#12]
Any objection to commit file generated by `SKIP_OKBUCK=0 ./gradlew -Dokbuck.wrapper=true okbuck --no-configuration-cache` directly to the repo?

**Comment by oliviernotteghem** [comment]
It would be great, unfortunately OkBuck creates a symlink to gradle cache which is outside our repo. So we need to run the OkBuck locally.

```
> readlink  .okbuck/workspace/buck_binary/buck-a68ef0d834eec5fe381cb3e8e8612ba9fa42a09d.pex
/Users/oliviern/.gradle/caches/modules-2/files-2.1/com.github.facebook/buck/a68ef0d834eec5fe381cb3e8e8612ba9fa42a09d/5450c19097d5096ad77215b56e255d6bf79277c9/buck-a68ef0d834eec5fe381cb3e8e8612ba9fa42a09d.pex
```

**Comment by runningcode** [comment]
Just wanted to confirm that we want to keep all these files in the repo?
By default okbuck projects should use the following ignores: https://github.com/uber/okbuck/blob/master/.gitignore#L14
