### ISSUE TITLE
Benchmark image missing axes label

### ISSUE THREAD

**Issue by zsiegel** [uber-common/android-build-eval#2]
Hello

It appears the axes labels on the benchmark results image were cut off.

https://github.com/uber-common/android-build-eval/blob/master/output/mobile_app1.png

Any chance this could get updated? It be great to see the labels in full. Thanks for this project excited to checkout the results and the configurations.

**Comment by chao2zhang** [comment]
I think the x-axis is "scenario" while y-axis is milliseconds.

**Comment by oliviernotteghem** [comment]
Thanks for bringing up, @zsiegel ! "scenario" got indeed truncated and it's not clear that the build time is in msec. Will fix this today.
